parameters:
    redis.manager.class: Euskadi31\Bundle\RedisBundle\Redis\RedisManager
    session.handler.redis.class: Euskadi31\Bundle\RedisBundle\Redis\RedisSessionHandler
    session.native.handler.redis.class: Euskadi31\Bundle\RedisBundle\Redis\NativeRedisSessionHandler
    swiftmailer.spool.redis.class: Euskadi31\Bundle\RedisBundle\SwiftMailer\RedisSpool
    session_lifetime: 3600
services:
    swiftmailer.spool.redis:
        class: '%swiftmailer.spool.redis.class%'
        calls:
            - [setRedis, ['@redis']]
            - [setKey, ["swiftmailer"]]
            - [setLogger, ['@?logger']]
        tags:
            - { name: monolog.logger, channel: redis }
    redis.manager:
        class: '%redis.manager.class%'
        arguments: ['%redis%']
        calls:
            - [setLogger, ['@?logger']]
        tags:
            - { name: monolog.logger, channel: redis }
    redis:
        class: Redis
        factory_service: redis.manager
        factory_method: getRedis
    session.handler.redis:
        class:     '%session.handler.redis.class%'
        arguments: ['@redis', '%session_lifetime%']
        calls:
            - [setLogger, ['@?logger']]
        tags:
            - { name: monolog.logger, channel: redis }
    session.native.handler.redis:
        class: '%session.native.handler.redis.class%'
        arguments: ['@redis']
